# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seohyun/mychat/MychatServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seohyun/mychat/MychatServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seohyun/mychat/MychatServer/CMakeFiles /home/seohyun/mychat/MychatServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seohyun/mychat/MychatServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MychatServer

# Build rule for target.
MychatServer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MychatServer
.PHONY : MychatServer

# fast build rule for target.
MychatServer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/build
.PHONY : MychatServer/fast

base/ConfigFileReader.o: base/ConfigFileReader.cpp.o
.PHONY : base/ConfigFileReader.o

# target to build an object file
base/ConfigFileReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/base/ConfigFileReader.cpp.o
.PHONY : base/ConfigFileReader.cpp.o

base/ConfigFileReader.i: base/ConfigFileReader.cpp.i
.PHONY : base/ConfigFileReader.i

# target to preprocess a source file
base/ConfigFileReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/base/ConfigFileReader.cpp.i
.PHONY : base/ConfigFileReader.cpp.i

base/ConfigFileReader.s: base/ConfigFileReader.cpp.s
.PHONY : base/ConfigFileReader.s

# target to generate assembly for a file
base/ConfigFileReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/base/ConfigFileReader.cpp.s
.PHONY : base/ConfigFileReader.cpp.s

chatserversrc/ChatServer.o: chatserversrc/ChatServer.cpp.o
.PHONY : chatserversrc/ChatServer.o

# target to build an object file
chatserversrc/ChatServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/ChatServer.cpp.o
.PHONY : chatserversrc/ChatServer.cpp.o

chatserversrc/ChatServer.i: chatserversrc/ChatServer.cpp.i
.PHONY : chatserversrc/ChatServer.i

# target to preprocess a source file
chatserversrc/ChatServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/ChatServer.cpp.i
.PHONY : chatserversrc/ChatServer.cpp.i

chatserversrc/ChatServer.s: chatserversrc/ChatServer.cpp.s
.PHONY : chatserversrc/ChatServer.s

# target to generate assembly for a file
chatserversrc/ChatServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/ChatServer.cpp.s
.PHONY : chatserversrc/ChatServer.cpp.s

chatserversrc/ChatSession.o: chatserversrc/ChatSession.cpp.o
.PHONY : chatserversrc/ChatSession.o

# target to build an object file
chatserversrc/ChatSession.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/ChatSession.cpp.o
.PHONY : chatserversrc/ChatSession.cpp.o

chatserversrc/ChatSession.i: chatserversrc/ChatSession.cpp.i
.PHONY : chatserversrc/ChatSession.i

# target to preprocess a source file
chatserversrc/ChatSession.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/ChatSession.cpp.i
.PHONY : chatserversrc/ChatSession.cpp.i

chatserversrc/ChatSession.s: chatserversrc/ChatSession.cpp.s
.PHONY : chatserversrc/ChatSession.s

# target to generate assembly for a file
chatserversrc/ChatSession.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/ChatSession.cpp.s
.PHONY : chatserversrc/ChatSession.cpp.s

chatserversrc/main.o: chatserversrc/main.cpp.o
.PHONY : chatserversrc/main.o

# target to build an object file
chatserversrc/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/main.cpp.o
.PHONY : chatserversrc/main.cpp.o

chatserversrc/main.i: chatserversrc/main.cpp.i
.PHONY : chatserversrc/main.i

# target to preprocess a source file
chatserversrc/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/main.cpp.i
.PHONY : chatserversrc/main.cpp.i

chatserversrc/main.s: chatserversrc/main.cpp.s
.PHONY : chatserversrc/main.s

# target to generate assembly for a file
chatserversrc/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/chatserversrc/main.cpp.s
.PHONY : chatserversrc/main.cpp.s

utils/Daemon.o: utils/Daemon.cpp.o
.PHONY : utils/Daemon.o

# target to build an object file
utils/Daemon.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/utils/Daemon.cpp.o
.PHONY : utils/Daemon.cpp.o

utils/Daemon.i: utils/Daemon.cpp.i
.PHONY : utils/Daemon.i

# target to preprocess a source file
utils/Daemon.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/utils/Daemon.cpp.i
.PHONY : utils/Daemon.cpp.i

utils/Daemon.s: utils/Daemon.cpp.s
.PHONY : utils/Daemon.s

# target to generate assembly for a file
utils/Daemon.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MychatServer.dir/build.make CMakeFiles/MychatServer.dir/utils/Daemon.cpp.s
.PHONY : utils/Daemon.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MychatServer"
	@echo "... base/ConfigFileReader.o"
	@echo "... base/ConfigFileReader.i"
	@echo "... base/ConfigFileReader.s"
	@echo "... chatserversrc/ChatServer.o"
	@echo "... chatserversrc/ChatServer.i"
	@echo "... chatserversrc/ChatServer.s"
	@echo "... chatserversrc/ChatSession.o"
	@echo "... chatserversrc/ChatSession.i"
	@echo "... chatserversrc/ChatSession.s"
	@echo "... chatserversrc/main.o"
	@echo "... chatserversrc/main.i"
	@echo "... chatserversrc/main.s"
	@echo "... utils/Daemon.o"
	@echo "... utils/Daemon.i"
	@echo "... utils/Daemon.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

